# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:2.0.0-sdk

options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          caches:
          - dotnetcore      
          script:
          - export DOCKER_ENV=production
          - chmod -R a+x scripts
          - ./scripts/dotnet-build.sh
          - ./scripts/dotnet-test.sh
          - ./scripts/dotnet-publish.sh
          - ./scripts/docker-publish-pipelines.sh
          - ./scripts/after-success.sh
    develop:
      - step:
          caches:
          - dotnetcore      
          script:
          - export DOCKER_ENV=development
          - chmod -R a+x scripts
          - ./scripts/dotnet-build.sh
          - ./scripts/dotnet-test.sh
          - ./scripts/dotnet-publish.sh
          - ./scripts/docker-publish-pipelines.sh
          - ./scripts/after-success.sh